### ISSUE TITLE
Not working with gnome-shell 3.32

### ISSUE THREAD

**Issue by matclab** [projecthamster/shell-extension#307]
This nice extension does not work anymore on gnome-shell 3.32.
logs say:
```
JS ERROR: TypeError: this.factsBox is undefined
                  _refresh@/home/matclab/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:191:3
                  asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:133:13
```

**Comment by ldoktor** [comment]
I'm using version with https://github.com/projecthamster/hamster-shell-extension/pull/299 and getting a different error:

```
bře 28 18:53:47 localhost.localdomain gnome-shell[14920]: JS ERROR: TypeError: this._construct is not a function
                                                           newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
                                                           _init@/home/medic/.local/share/gnome-shell/extensions/contact@projecthamster.org/widgets/panelWidget.js:102:25
                                                           wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                                           deferred_enable@/home/medic/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:143:32
                                                           Controller/enable/<@/home/medic/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js:132:21
                                                           _makeProxyWrapper/</<@resource:///org/gnome/gjs/modules/overrides/Gio.js:243:21
```

But also does not work. I depend on this plugin, but unfortunately don't know javascript enough to fix it. Would someone please take a look at this? I'm open to some form of donation...

**Comment by ernestask** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361 and https://gitlab.gnome.org/GNOME/gnome-shell-extensions/commit/bab4be1a597226a5fe8a29dcf3848be47e16a5e5 should be a start.

Edit: also https://gitlab.gnome.org/GNOME/gnome-shell-extensions/commit/ba27cc4a64daf7f62174653362741de30c2f5b86

**Comment by ldoktor** [comment]
Thank you, another source of information could be another extension I can't live without that had been already ported: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/510

**Comment by aldomann** [comment]
@ernestask's branch works great on my system.

**Comment by wolffi** [comment]
Works great. Thanks a lot @ernestaks! A minor inconvenience, auto-completion does not seem to work in the "What are you doing" dialog.

**Comment by ernestask** [comment]
I’m pretty sure there should be something in the journal in that case. Otherwise, I am not really interested in further working on this.

**Comment by jimmytheneutrino** [comment]
Guys, it's been 3 months and we have 2 functional PR versions available. This is, IMHO, the best time tracker for Gnome but it does feel that it is a bit under-loved right now (the latest commit to the main repo was more than one year ago). 

Could somebody please look into this, @elbenfreund, @tstriker, @FredericGuilbault? Maybe guys from the main hamster repo could help, @ederag, @GeraldJansen ?

Maybe one of the PR authors @ernestask, @hedayat or @mwilck might want to become new maintainers?

**Comment by ernestask** [comment]
> Maybe one of the PR authors @ernestask, @hedayat or @mwilck might want to become new maintainers?

Not particularly. Only looked into this because a distant colleague was having issues.

**Comment by mwilck** [comment]
I have no ambition to become the maintainer of this extension. I'm currently maintaining hamster for openSUSE (I'm much more into Python than Javascript). For openSUSE, I decided to package the extension as RPM to compensate for it being missing on the GNOME extensions web site.

I guess in theory, anyone of us could submit an update to extensions.gnome.org. We should be aware that the 3.32 and 3.30 versions are strictly incompatible though; not sure how other extension writers handle that. 3.32 users are probably still the minority today. Does extensions.gnome.org handle the GNOME version dependencies automatically somehow, I mean, is it possible to submit the same extension multiple times, for multiple GNOME shell versions?

**Comment by aldomann** [comment]
@mwilck as far as I'm concerned (if the UI is any indication), the website does handle different versions of a same extension, as it in fact allows your to download different versions of a given extension (tagged by the version of GS it's compatible with). 

I think the problem would be that it has to be the original developer the one who submits an updated version. A possible solution would be to just have it as a new extension instead.

**Comment by ederag** [comment]
> Maybe guys from the main hamster repo could help

Well, maintaining the [main original hamster](https://github.com/projecthamster/hamster)
is already eating too much of my time, so no thanks :wink:
I'll just make sure that the dbus interface stays compatible.
Thanks to this dbus interface, this extension is well separated,
so it is perfect to have a distinct maintainer.

**Comment by hedayat** [comment]
I'm also not someone who can be a real maintainer for this extension. However, if maintaining would mean accepting merge requests and trying to solve small bugs; it'd be possible (I was already thinking about creating a fork with such a goal for myself). But, I'm really not a Javascript guy, and certainly not a good maintainer for this project specially officially. And... there is no need to have a single maintainer. :P I'd be more than willing to help with maintaining this project as far as my time permits.

**Comment by FredericGuilbault** [comment]
I also think it's the best time tracker for linux  But Im out of this project. 

I have worked on a rewrite of hamster project in nodejs. https://gitlab.com/FredericGuilbault/gerboise  But at this point it berly usable. So not much of a solution ATM. 

---
IMO, at this point of abandon,  whatever @hedayat do, it's better then nothing so  +1

It been few years alerady but I remember there was some code shared between hamster-shell-extension and the cinamon version of this plugin. Then, cinnamon people asked to become maintainers of their projectHamster extention and integrated it in their big repo who contain all the cinnamon applets. That's a thing I recall.

**Comment by mwilck** [comment]
Sounds good to me too. @hedayat, I'd be willing to help as time and abilities permit, but like you I'm  also not a Javascript guy. I have personal interest to make sure the extension works. It's a shame that maintaining extensions is being made so difficult by the core developers.

**Comment by FredericGuilbault** [comment]
it is.

**Comment by aldomann** [comment]
@FredericGuilbault are you still working on Gerboise?

**Comment by GeraldJansen** [comment]
A simple, alternative gnome-shell extension could be constructed with https://github.com/p-e-w/argos and Hamster CLI commands. That would require less maintenance because Argos is well maintained for Gnome updates.

**Comment by matclab** [comment]
@GeraldJansen Good idea… I've done a very rough first implementation which depends on xsv and piep (I'll probably do a pure python implementation later) : 

It proposes to choose an activy among one of the last 14 days. You may still add new activity with hamster CLI.

```sh
#!/bin/sh

LC_ALL=C hamster current \
   | piep "p if p == 'No activity' else p.split(',')[0].split()[2:]"
echo "---"
now=$(date +%Y-%m-%d)
last=$(date +%Y-%m-%d -d "14 days ago")
echo "Stop | terminal=false refresh=true bash='hamster stop'"
LC_ALL=C hamster export tsv "$last" "$now"  \
   | xsv select -d"\t" "activity,category,description,tags" | xsv sort \
   | tail -n+2 | uniq \
   | piep "p.splitcomma()|l=f'#{p[3]}' if p[3] else ''
	    | f'{p[0]}@{p[1]},{p[2]} {l}' | p.strip(', ')
	    | p + f' | terminal=false refresh=true bash=\'hamster start \"{p}\"\''"

```

**Comment by FredericGuilbault** [comment]
@aldomann   Yes I do, Quite slowly, but im still on it. I had many trouble with nwjs + sqlite. 
Gerboise is far from ready for production in term of functionality, code quality and stability. but That's what I use ATM. 

It be more motivating if I had users/contributors/interested people.

**Comment by aldomann** [comment]
I've made a more polished version of @matclab's Argos script trying to replicate `hamster-shell-extension`'s UX as much as possible. 

```bash
#!/bin/sh

# Top bar status
LC_ALL=C hamster current \
	| piep "' | iconName=media-playback-start-symbolic' if p == 'No activity' else ' | iconName=media-playback-stop-symbolic'"
echo "---"

# Print current activity
echo "Current activity | size=10 | color=#919191"
LC_ALL=C hamster current \
	| piep "p if p == 'No activity' else p.split(',')[0].split()[2:]"
# Stop current activity
LC_ALL=C hamster current \
	| piep "'Stop Tracking | terminal=false refresh=true bash=\'hamster stop\'' if p != 'No activity' else ''"

# Get list of recent activities
now=$(date +%Y-%m-%d)
last=$(date +%Y-%m-%d -d "14 days ago")
echo "Recent activities | size=10 | color=#919191"
LC_ALL=C hamster export tsv "$last" "$now"  \
	| xsv select -d"\t" "activity,category,description,tags" | xsv sort \
	| tail -n+2 | uniq \
	| piep "p.splitcomma()|l=f'#{p[3]}' if p[3] else ''
		| f'{p[0]}@{p[1]},{p[2]} {l}' | p.strip(', ')
		| '--' + p + f' | terminal=false refresh=true bash=\'hamster start \"{p}\"\''"

# Additional GUI options
echo "---"
echo "Show Overview | terminal=false refresh=true bash='hamster overview'"
echo "Add Earlier Activity | terminal=false refresh=true bash='hamster add'"
```

![image](https://user-images.githubusercontent.com/729732/66327764-473fc700-e923-11e9-850d-e1fb2c59ae03.png) 
![image](https://user-images.githubusercontent.com/729732/66327835-650d2c00-e923-11e9-9f9b-7cf3ca40ec03.png)


**Some points to keep in mind:**
- I'm using Hamster 2.2.2 (which allows to use the "Add Earlier Activity" button; I couldn't figure out the command on Hamster 1.X).
- I'm using just using icons on the top bar (stop/play), as that's how I've always used the extension.

**Missing features**
- Option to change the appearance on the top panel.
- Adding a shortcut (not sure if Argos allows this).

**Comment by matclab** [comment]
And here is a pure python version expanding on @aldomann one: https://gist.github.com/matclab/3a36d46e16bee776d0739292bcacaa9b
I'll try to do a proper git repo…

**Comment by aldomann** [comment]
Didn't realise Argos supported Python. That's great, since bash can be a bit messy for some more complex stuff.

**Comment by mwilck** [comment]
@matclab, nice work in incredibly little time! 

Yet AFAICS it's still missing the features I need most about the extension - being able to type in a new activitiy (with autocompletion) and the "edit activity" buttons.

So for the time being, I hope the JS extension can be repaired once more.

**Comment by matclab** [comment]
@mwilck unfortunately Argos does not allow for easy user input. However, I've added a "+" icon in order to launch the hamster UI for adding new action with completion.
It only works well with hamster v2+, as hamster 1.04 does not quit once the window is closed, which gives a lot unused background process after some times.

The new version has its own repo: https://github.com/matclab/argos-hamster-plugin, which will allow to discuss it there and stop polluting this issue.

**Comment by matclab** [comment]
Closing in favor of issue #315

**Comment by mwilck** [comment]
See #315 for a fix for GNOME 3.34.

**Comment by DirkHoffmann** [comment]
Solution for 3.32 (title of this issue!) is mentioned in [#315 (comment)](https://github.com/projecthamster/hamster-shell-extension/issues/315#issuecomment-586588367) and #301.
